name: Flutter CI

on:
  push:
    branches:
      - '!(master)'
  pull_request:
    branches:
      - '!(master)'
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .env
      run: |
        echo "MAPBOX_ACCESS_TOKEN=${{ secrets.MAPBOX_ACCESS_TOKEN }}" > .env
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '17'
    - uses: subosito/flutter-action@v2
      with:
        channel: stable
    # Set version in pubspec.yaml based on the CI build number
    - run: |
        VERSION=$(echo $GITHUB_RUN_NUMBER)
        sed -i -E "s/version: (.*?)\+(.*?)/version: \\1+$VERSION/g" pubspec.yaml
    - run: flutter pub get
    - run: flutter pub run build_runner build --delete-conflicting-outputs
    - run: flutter gen-l10n
    - run: flutter build appbundle --release
    - run: flutter test
