name: Flutter Build
on:
  push:
    branches:
      - master

jobs:
  build_android:
    uses: ./.github/workflows/flutter-build.yaml
    secrets: inherit

  upload_to_play_store:
    needs: build_android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Decrypt keystore
        run: |
          mkdir -p android/app
          openssl aes-256-cbc -d -in android/upload.jks.enc -out android/app/upload.jks -k ${{ secrets.KEYSTORE_PASSWORD }}

      - name: Build Android App
        run: flutter build appbundle --release

      - name: Upload to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
          packageName: it.denv.wanderlog_alt
          releaseFile: build/app/outputs/bundle/release/app-release.aab
          track: production
